# Akash SDL for GPU-accelerated RandomX zkVM proving
# Deploy with: akash tx deployment create deploy.yaml --from wallet --chain-id akashnet-2
#
# This requests a GPU instance to run zkVM proving with CUDA acceleration.
# Estimated cost: ~$0.50-2.00/hour depending on GPU type

---
version: "2.0"

services:
  randomx-zkvm:
    image: ghcr.io/YOUR_USERNAME/randomx-zkvm-gpu:latest  # Replace with your image
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
    env:
      - RISC0_PROVER=cuda
      - RUST_LOG=info

profiles:
  compute:
    randomx-zkvm:
      resources:
        cpu:
          units: 4
        memory:
          size: 16Gi
        storage:
          size: 50Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx3080
                - model: rtx3090
                - model: rtx4080
                - model: rtx4090
                - model: a100
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        randomx-zkvm:
          denom: uakt
          amount: 10000  # ~$2/hour max bid

deployment:
  randomx-zkvm:
    akash:
      profile: randomx-zkvm
      count: 1
