---
version: "2.0"

services:
  randomx-zkvm:
    image: ghcr.io/zenopie/zkvm-test:gpu-v11
    env:
      - RISC0_PROVER=local
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    expose:
      - port: 8080
        as: 80
        to:
          - global: true

profiles:
  compute:
    randomx-zkvm:
      resources:
        cpu:
          units: 8
        memory:
          size: 32Gi
        storage:
          size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: a100
                - model: rtx4090
                - model: rtx3090
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
          - akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4
      pricing:
        randomx-zkvm:
          denom: uakt
          amount: 10000

deployment:
  randomx-zkvm:
    akash:
      profile: randomx-zkvm
      count: 1
